format = "$directory$git_branch$git_status$character"

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "../"
format = "[$path]($style) "
style = "cyan"

[git_branch]
symbol = "îœ¥ "
format = "[$symbol$branch]($style) "
style = "purple"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style) )"
style = "red"
stashed = ""

[character]
success_symbol = '[\$](bold #5cf870)'
error_symbol = '[\$](bold red)'
